### ISSUE TITLE
Feature request or help porting to other bitcoin-like cryptocurrencies

### ISSUE THREAD

**Issue by johnbailon** [BitonicNL/verify-signed-message#1]
Hi, I'm trying to port this package to litecoin (with eventual goal of supporting more bitcoin-like cryptocurrencies).

At first glance, this sounds like a trivial endeavor, given that **ltcsuite** promises to be a "drop-in" replacement to **btcsuite**,  but I'm running into issues when [validating P2SH](https://github.com/BitonicNL/verify-signed-message/blob/f2aac6d16bef9185d6d2100d4bda88450c404d67/internal/validation.go#L32).

Given a known to be correct signature by address `MS6B3BusQyWAegcmMcTy8LHUEWorUiQArL`, this is what I get:
```
generated address 'MTYpLNp8TTjavitJHqnpyPpCMABd53EB1T' does not match expected address 'MS6B3BusQyWAegcmMcTy8LHUEWorUiQArL'
```

Any pointers? I feel like I am missing something unique to how litecoin generates P2SH.

**Comment by ArbitronNL** [comment]
We only support Bitcoin. Underwater we use [`btcsuite/btcd`](https://github.com/btcsuite/btcd), so we recommend looking into their codebase.
