### ISSUE TITLE
Any golang lib support bip322 sign verify?

### ISSUE THREAD

**Issue by xiaoshengaimm** [BitonicNL/verify-signed-message#4]
Any golang lib support bip322 sign verify?

**Comment by Orange881** [comment]
+1

**Comment by ArbitronNL** [comment]
Not that we know off, sorry.

**Comment by trevormil** [comment]
> Any golang lib support bip322 sign verify?

Ever find anything?

**Comment by ArbitronNL** [comment]
This package now has very basic BIP-322 support. Contributions to it are very welcome.
