### ISSUE TITLE
cannot use P2TR for recovery flag 'compressed'

### ISSUE THREAD

**Issue by leotons** [BitonicNL/verify-signed-message#5]
tests := map[string]verifier.SignedMessage{
		"p2tr": {
			Address:   "bc1p5wwxjuvaxp5jcpg82ys7kupg0gtnavp5u3fje8c7vs3a2dvzpjqs2xtq4h",
			Message:   "111111",
			Signature: "IBs2/wEHrUMdayrR+eQKCwfDCDu7FRVvZBkDi6NODP4mTvpIppdut6mIbmF8Ph6YS+v2cp0LpsLq59tHiaAPYqQ=",
		},
	}
	// Bitcoin Testnet3
	fmt.Println(verifier.Verify(tests["p2tr"]))

**Comment by ArbitronNL** [comment]
After double checking with Sparrow this is indeed a [valid BIP322](https://github.com/BitonicNL/verify-signed-message/assets/74659821/7f3c56e8-4adc-497b-bad4-532114dd1c53) signed message. However, BIP322 is _not yet_ supported by this library (as mentioned in the README and in a [another issue](https://github.com/BitonicNL/verify-signed-message/issues/4)).

If you need it right now, feel free to make a pull request to add support.

**Comment by ArbitronNL** [comment]
We now support compressed P2TR and added very basic BIP-322 support. Contributions to expand it further are welcome.
